version: 1
formatters:
  default:
    format: "[{asctime}][{rank}][{name}][{levelname}] {message}"
    datefmt: "%y%m%d %H:%M:%S"
    style: '{'
handlers:
  console:
    class: tools.logger.TqdmHandler
    formatter: default
    level: INFO
  file:
    class: logging.FileHandler
    formatter: default
    level: DEBUG
root:
  level: NOTSET
  handlers: [console, file]
disable_existing_loggers: false






